version: '3'

services:

  fript-web:
    build: .
    container_name: fript-web
    ports:
      - "3000:3000"
    volumes:
      - ./:/opt/fript-web

  fript-api:
    container_name: fript-api
    build: ../fript-api
    volumes:
      - ../fript-api/:/opt/fript-api
